EXEC sp_readerrorlog 0,1, 'listening'
EXEC sp_readerrorlog 1,1, 'listening'
EXEC sp_readerrorlog 2,1, 'listening'
EXEC sp_readerrorlog 3,1, 'listening'

-- EXEC sp_readerrorlog 0,1, '_NORMAL'
EXEC sp_readerrorlog 0,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 1,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 2,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 3,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 4,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 5,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 6,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 7,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 8,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 9,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 10,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 11,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 12,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 13,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 14,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 15,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 16,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 17,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 18,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 19,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 20,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 21,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 22,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 23,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 24,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 25,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 26,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 27,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 28,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 29,1, 'PRIMARY_NORMAL'' to'
EXEC sp_readerrorlog 30,1, 'PRIMARY_NORMAL'' to'

